field_english_to_french_dic = {
    "id": "id",
    "name": "Nom",
    "description": "Description",
    "application_name": "Application",
    "application_long_name": "Application (long)",
    "family_name": "Famille",
    "tag_name": "Tag",
    "reutilization_name": "Réutilisation",
    "type_name": "Type",
    "example": "Exemple",
    "referentiel_name": "Référentiel",
    "sensibility_name": "Sensibilité",
    "open_data_name": "OpenData",
    "database_name": "Base/index",
    "database_table_name": "Table",
    "database_table_count": "Nb tables",
    "fields": "Champ",
    "field_count": "Nb champs",
    "volumetry": "Volumétrie",
    "volumetry_comment": "Commentaire sur la volumétrie",
    "monthly_volumetry": "Production par mois",
    "monthly_volumetry_comment": "Commentaire sur la  production par mois",
    "update_frequency_name": "Mise à jour",
    "conservation": "Conservation",
    "classification_name": "Axes d'analyse",
    "exposition_name": "Exposition",
    "origin_name": "Origine",
    "created_at": "Date de création",
    "updated_at": "Date de modification",
    "source_data_update": "Date de modification des données",
    "goals": "Finalités",
    "access_url": "Accès",
    "operator_count": "Nb opérateurs",
    "operator_count_comment": "Commentaire sur le nb d'opérateurs",
    "user_count": "Nb utilisateurs",
    "user_count_comment": "Commentaire sur le nb utilisateurs",
    "monthly_connection_count": "Nb connexion par mois",
    "monthly_connection_count_comment": "Commentaire sur le nb connexion par mois",
    "context_email": "Contact",
    "validation_date": "Date de validation",
    "category": "Catégorie",
    "full_path": "Valeur",
    "label": "Libellé",
    "organization_name": "Organisation",
    "first_name": "Prénom",
    "last_name": "Nom de famille",
    "email": "Email",
    "is_admin": "Administrateur ?",
    "password_hash": "Mot de passe",
    "owners": "Administrateurs",
    "historic": "Historique",
    'origin_application_name': "Application source",
    'data_source_count': 'Nombre de données',
    "is_reference": "Donnée référentielle",
    "long_name": "Nom long",
    "key":"clé",
    "namespace":"namespace",
    "value":"valeur",
    "referentiel_count":"Nombre de référentiels utilisés",
    "reutilization_count":"Nombre de réutilisations",
    "application_description_level":"Niveau de description de l'application",
    "datasource_description_level":"Niveau de description des données",
    "text_query": "Recherche textuelle",
    "text_operator": "Type de recherche textuelle",
    "exclusion": "Exclusion",
    "filters_query": "Filtre",
    "date": "Date",
    "pathname": "URL",
    "subpath": "Complément d'URL",
    "search": "Recherche",
    "is_general_admin": "Administrateur général?",
    "is_simple_admin": "Administrateur?",

}

field_french_to_english_dic = {
    "id": "id",
    "Nom": "name",
    "Description": "description",
    "Application": "application_name",
    "Application (long)": "application_long_name",
    "Famille": "family_name",
    "Tag": "tag_name",
    "Réutilisation": "reutilization_name",
    "Type": "type_name",
    "Exemple": "example",
    "Référentiel": "referentiel_name",
    "Sensibilité": "sensibility_name",
    "OpenData": "open_data_name",
    "Base/index": "database_name",
    "Table": "database_table_name",
    "Nb tables": "database_table_count",
    "Champ": "fields",
    "Nb champs": "field_count",
    "Volumétrie": "volumetry",
    "Commentaire sur la volumétrie": "volumetry_comment",
    "Production par mois": "monthly_volumetry",
    "Commentaire sur la  production par mois": "monthly_volumetry_comment",
    "Mise à jour": "update_frequency_name",
    "Conservation": "conservation",
    "Axes d'analyse": "classification_name",
    "Exposition": "exposition_name",
    "Origine": "origin_name",
    "Date de création": "created_at",
    "Date de modification": "updated_at",
    "Date de modification des données": "source_data_update",
    "Finalités": "goals",
    "Accès": "access_url",
    "Nb opérateurs": "operator_count",
    "Commentaire sur le nb d'opérateurs": "operator_count_comment",
    "Nb utilisateurs": "user_count",
    "Commentaire sur le nb utilisateurs": "user_count_comment",
    "Nb connexion par mois": "monthly_connection_count",
    "Commentaire sur le nb connexion par mois": "monthly_connection_count_comment",
    "Contact": "context_email",
    "Date de validation": "validation_date",
    "Catégorie": "category",
    "Valeur": "full_path",
    "Libellé": "label",
    "Organisation": "organization_name",
    "Prénom": "first_name",
    "Nom de famille": "last_name",
    "Email": "email",
    "Administrateur ?": "is_admin",
    "Mot de passe": "password_hash",
    "Administrateurs": "owners",
    "Historique": "historic",
    'Application source': "origin_application_name",
    'Nombre de données': 'data_source_count',
    "Donnée référentielle": "is_reference",
    "Nom long": "long_name",
    "clé":"key",
    "namespace":"namespace",
    "valeur":"value",
    "Nombre de référentiels utilisés":"referentiel_count",
    "Nombre de réutilisations":"reutilization_count",
    "Niveau de description de l'application":"application_description_level",
    "Niveau de description des données":"datasource_description_level"
}


enumeration_french_to_english = {
    "Tag": "tag",
    "Famille": "family",
    "Type": "type",
    "Référentiel": "referentiel",
    "Sensibilité": "sensibility",
    "OpenData": "open_data",
    "Mise à jour": "update_frequency",
    "Origine": "origin",
    "Exposition": "exposition",
    "Organisation": "organization",
    "Axes d'analyse": "classification"
}

enumeration_english_to_french = {
    "tag": "Tag",
    "family": "Famille",
    "referentiel": "Référentiel",
    "sensibility": "Sensibilité",
    "open_data": "OpenData",
    "update_frequency": "Mise à jour",
    "origin": "Origine",
    "type": "Type",
    "exposition": "Exposition",
    "classification": "Axes d'analyse",
    "organization": "Organisation"
}

FULL_PATH_DELIMITER = '>'

DATASOURCE_ORIGINAL_FIELDS_ID = [
    'name',
    'description',
    'application_id',
    'reutilizations',
    'family_name',
    'tag_name',
    'type_name',
    'example',
    'sensibility_name',
    'open_data_name',
    'database_name',
    'database_table_name',
    'database_table_count',
    'fields',
    'field_count',
    'volumetry',
    'volumetry_comment',
    'monthly_volumetry',
    'monthly_volumetry_comment',
    'update_frequency_name',
    'conservation',
    'classification_name',
    'exposition_name',
    'origin_name',
    'origin_applications',
    'is_reference'
]

DATASOURCE_ID_NO_COMMENT =  [field for field in DATASOURCE_ORIGINAL_FIELDS_ID if (field not in ['volumetry_comment','monthly_volumetry_comment', 'is_reference'])]
