"""add data_source_name and application_name in routingKpi

Revision ID: 46ce46c6bcda
Revises: b823920f67b6
Create Date: 2023-01-17 14:58:25.884889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ce46c6bcda'
down_revision = 'b823920f67b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routingKPI', sa.Column('application_name', sa.String(), nullable=True))
    op.add_column('routingKPI', sa.Column('data_source_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routingKPI', 'data_source_name')
    op.drop_column('routingKPI', 'application_name')
    # ### end Alembic commands ###
