"""unique application name

Revision ID: 56ae3b6a8cf0
Revises: d7982c8b8229
Create Date: 2022-11-02 17:11:08.177816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ae3b6a8cf0'
down_revision = 'd7982c8b8229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_unique_constraint("application_name_unique", 'application', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_constraint("application_name_unique", 'application', type_='unique')
    # ### end Alembic commands ###
