"""browsing kpi

Revision ID: 5f95f134356d
Revises: d7982c8b8229
Create Date: 2022-11-02 12:03:37.349794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f95f134356d'
down_revision = 'd7982c8b8229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routingKPI',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pathname', sa.String(), nullable=False),
    sa.Column('subpath', sa.String(), nullable=False),
    sa.Column('search', sa.String(), nullable=False),
    sa.Column('is_general_admin', sa.Boolean(), nullable=False),
    sa.Column('is_simple_admin', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchingKPI',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_query', sa.String(), nullable=True),
    sa.Column('text_operator', sa.String(), nullable=True),
    sa.Column('exclusion', sa.String(), nullable=True),
    sa.Column('filters_query', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchingKPI')
    op.drop_table('routingKPI')
    # ### end Alembic commands ###
