"""add new table WildCard for config strings

Revision ID: d7982c8b8229
Revises: dfee9776774b
Create Date: 2022-09-12 16:35:22.832048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7982c8b8229'
down_revision = 'dfee9776774b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wild_card',
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('namespace', 'key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wild_card')
    # ### end Alembic commands ###
