"""adding parent id to filters

Revision ID: db4371acae5e
Revises: 1b6f47c6e77a
Create Date: 2022-05-30 14:57:34.387069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4371acae5e'
down_revision = '1b6f47c6e77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposition', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exposition', 'exposition', ['parent_id'], ['id'])
    op.add_column('family', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'family', 'family', ['parent_id'], ['id'])
    op.add_column('open_data', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'open_data', 'open_data', ['parent_id'], ['id'])
    op.add_column('organization', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization', 'organization', ['parent_id'], ['id'])
    op.add_column('origin', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'origin', 'origin', ['parent_id'], ['id'])
    op.add_column('sensibility', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensibility', 'sensibility', ['parent_id'], ['id'])
    op.add_column('tag', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'tag', ['parent_id'], ['id'])
    op.add_column('type', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'type', 'type', ['parent_id'], ['id'])
    op.add_column('update_frequency', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'update_frequency', 'update_frequency', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'update_frequency', type_='foreignkey')
    op.drop_column('update_frequency', 'parent_id')
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.drop_column('type', 'parent_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'parent_id')
    op.drop_constraint(None, 'sensibility', type_='foreignkey')
    op.drop_column('sensibility', 'parent_id')
    op.drop_constraint(None, 'origin', type_='foreignkey')
    op.drop_column('origin', 'parent_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'parent_id')
    op.drop_constraint(None, 'open_data', type_='foreignkey')
    op.drop_column('open_data', 'parent_id')
    op.drop_constraint(None, 'family', type_='foreignkey')
    op.drop_column('family', 'parent_id')
    op.drop_constraint(None, 'exposition', type_='foreignkey')
    op.drop_column('exposition', 'parent_id')
    # ### end Alembic commands ###
