name: Cartographie des données MI

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - uses: actions/checkout@v3
    - name: Install scalingo CLI
      run: curl -O https://cli-dl.scalingo.io/install && bash install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build --production
    - name: Setup frontend/backend directory
      run: |
        cp -R ./backend/ ./out/
        cp -R ./frontend/build/ ./out/build/
    - name: Build backend
      run: tar -cvzf backend.tar.gz ./out
    - name: Deploy to Scalingo
      run: |
        scalingo login --api-token=${{secrets.SCALINGO_API_TOKEN}}
        scalingo --app=${{secrets.SCALINGO_APP_NAME}} --region=${{secrets.SCALINGO_REGION}} deploy backend.tar.gz
